import type { Metadata } from "next";
import Script from "next/script";
import {
  Geist_Mono,
  Fjalla_One,
  Homemade_Apple
} from "next/font/google";
import "./globals.css";
import { TransitionProvider } from "./components/transition_provider";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const fjallaOne = Fjalla_One({
  variable: "--font-fjalla-one",
  subsets: ["latin"],
  weight: "400",
});

const homemadeApple = Homemade_Apple({
  variable: "--font-homemade-apple",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {process.env.NODE_ENV === 'development' && (
          <Script
            src="//unpkg.com/react-grab/dist/index.global.js"
            crossOrigin="anonymous"
            strategy="beforeInteractive"
            data-enabled="true"
          />
        )}
      </head>
      <body
        className={`${geistMono.variable} ${fjallaOne.variable} ${homemadeApple.variable} antialiased`}
      >
        <TransitionProvider
          colors={[
            'hsl(141, 78.9%, 85.1%)',
            'hsl(142.1, 76.2%, 36.3%)',
            'hsl(144.9, 80.4%, 10%)'
          ]}
          duration={3}
          stagger={0.6}
          direction="up"
        >
          {children}
        </TransitionProvider>
      </body>
    </html>
  );
}
