import path from "node:path";

export const REPO_ROOT = process.cwd();
export const SEO_DATA_DIR = process.env.SEO_DATA_DIR || path.join(REPO_ROOT, "data", "seo");
export const PUBLIC_DASHBOARD_DIR = path.join(REPO_ROOT, "public", "data", "seo-dashboard");

export const DEFAULTS = {
  site: process.env.SEO_GSC_SITE || "sc-domain:code-lieshout.nl",
  days: Number.parseInt(process.env.SEO_DAYS || "180", 10),
  period: process.env.SEO_PERIOD || "28d",
  limit: Number.parseInt(process.env.SEO_LIMIT || "50", 10),
  ga4Property: process.env.SEO_GA4_PROPERTY || "526910157",
  gscCli:
    process.env.SEO_GSC_CLI ||
    "/home/pimmetje/.hermes/profiles/seo/home/.local/bin/google-search-console-pp-cli",
  gscHome: process.env.SEO_GSC_HOME || "/home/pimmetje/.hermes/profiles/seo/home",
  ga4Command: process.env.SEO_GA4_COMMAND || "",
};

export const GSC_WORKFLOWS = [
  {
    id: "sync",
    label: "Sync",
    args: ({ site, days }) => [
      "sync",
      "--site",
      site,
      "--last",
      `${days}d`,
      "--dimensions",
      "date,query,page",
      "--with-sitemaps",
      "--json",
      "--no-input",
      "--no-color",
      "--yes",
    ],
  },
  {
    id: "quickWins",
    label: "Quick wins",
    args: ({ site, limit }) => [
      "quick-wins",
      site,
      "--position",
      "8-20",
      "--min-imps",
      "1",
      "--top",
      String(limit),
      "--json",
      "--no-input",
      "--no-color",
      "--yes",
    ],
  },
  {
    id: "cannibalization",
    label: "Cannibalization",
    args: ({ site, limit }) => [
      "cannibalization",
      site,
      "--min-imps",
      "1",
      "--top",
      String(limit),
      "--json",
      "--no-input",
      "--no-color",
      "--yes",
    ],
  },
  {
    id: "compare",
    label: "Compare",
    args: ({ site, period, limit }) => [
      "compare",
      site,
      "--period",
      period,
      "--vs",
      "prev-period",
      "--dim",
      "query",
      "--top",
      String(limit),
      "--json",
      "--no-input",
      "--no-color",
      "--yes",
    ],
  },
  {
    id: "decaying",
    label: "Decaying",
    args: ({ site, limit }) => [
      "decaying",
      site,
      "--window",
      "90d",
      "--min-imps",
      "1",
      "--top",
      String(limit),
      "--json",
      "--no-input",
      "--no-color",
      "--yes",
    ],
  },
  {
    id: "newQueries",
    label: "New queries",
    args: ({ site, period, limit }) => [
      "new-queries",
      site,
      "--since",
      period,
      "--min-imps",
      "1",
      "--top",
      String(limit),
      "--json",
      "--no-input",
      "--no-color",
      "--yes",
    ],
  },
  {
    id: "cliff",
    label: "Traffic cliffs",
    args: ({ site }) => [
      "cliff",
      site,
      "--metric",
      "clicks",
      "--threshold",
      "-20%",
      "--window",
      "14d",
      "--json",
      "--no-input",
      "--no-color",
      "--yes",
    ],
  },
  {
    id: "outliers",
    label: "CTR outliers",
    args: ({ site, limit }) => [
      "outliers",
      site,
      "--top",
      String(limit),
      "--json",
      "--no-input",
      "--no-color",
      "--yes",
    ],
  },
  {
    id: "sitemapWatch",
    label: "Sitemap watch",
    args: ({ site }) => [
      "sitemap-watch",
      site,
      "--json",
      "--no-input",
      "--no-color",
      "--yes",
    ],
  },
  {
    id: "coverageDrift",
    label: "Coverage drift",
    args: ({ site, period }) => [
      "coverage-drift",
      site,
      "--days",
      String(Math.max(1, Number.parseInt(period, 10) || 30)),
      "--json",
      "--no-input",
      "--no-color",
      "--yes",
    ],
  },
];
